channels:
- conda-forge
dependencies:
- python=3.10.15
- pip<=24.2
- pip:
  - mlflow==2.18.0
  - h2o==3.46.0.6
  - matplotlib==3.9.2
  - numpy==1.26.4
  - pandas==2.2.3
  - wcwidth==0.2.13
  - zipp==3.21.0
name: mlflow-env
